-- Migración 006: corrige Estado (región) y Localidad de las oficinas reales
-- con la lista canónica del negocio (86 oficinas). No borra ninguna oficina
-- existente -- solo actualiza estado/localidad de las que coinciden por
-- código, y agrega las que falten. Las entradas que no son oficinas reales
-- (herramientas, pagos, etc. que quedaron mezcladas por datos sucios del
-- Excel original) se dejan intactas, sin tocar.
--
-- Cómo aplicarla (una sola vez):
--   npx wrangler d1 execute vnet_fallas_masivas --remote --file=./migration_006_oficinas_estado_localidad.sql

UPDATE oficinas SET nombre = 'ACC - ACACIAS', estado = 'ZULIA', localidad = 'PUERTOS DE ALTAGRACIA' WHERE codigo = 'ACC';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('ACC', 'ACC - ACACIAS', 'ZULIA', 'PUERTOS DE ALTAGRACIA');
UPDATE oficinas SET nombre = 'ANA - ANACO', estado = 'ANZOATEGUI', localidad = 'ANACO' WHERE codigo = 'ANA';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('ANA', 'ANA - ANACO', 'ANZOATEGUI', 'ANACO');
UPDATE oficinas SET nombre = 'APD - ALTO PRADO', estado = 'MERIDA', localidad = 'ALTO PRADO' WHERE codigo = 'APD';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('APD', 'APD - ALTO PRADO', 'MERIDA', 'ALTO PRADO');
UPDATE oficinas SET nombre = 'BNO - BOCONO', estado = 'TRUJILLO', localidad = 'BOCONO' WHERE codigo = 'BNO';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('BNO', 'BNO - BOCONO', 'TRUJILLO', 'BOCONO');
UPDATE oficinas SET nombre = 'BRS - BARINAS', estado = 'BARINAS', localidad = 'BARINAS' WHERE codigo = 'BRS';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('BRS', 'BRS - BARINAS', 'BARINAS', 'BARINAS');
UPDATE oficinas SET nombre = 'BTA - BARUTA', estado = 'DISTRITO CAPITAL', localidad = 'CARACAS' WHERE codigo = 'BTA';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('BTA', 'BTA - BARUTA', 'DISTRITO CAPITAL', 'CARACAS');
UPDATE oficinas SET nombre = 'CAF - CAFETAL', estado = 'DISTRITO CAPITAL', localidad = 'CARACAS' WHERE codigo = 'CAF';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('CAF', 'CAF - CAFETAL', 'DISTRITO CAPITAL', 'CARACAS');
UPDATE oficinas SET nombre = 'CAT - CATIA', estado = 'DISTRITO CAPITAL', localidad = 'CARACAS' WHERE codigo = 'CAT';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('CAT', 'CAT - CATIA', 'DISTRITO CAPITAL', 'CARACAS');
UPDATE oficinas SET nombre = 'CAU - CAURIMARE', estado = 'DISTRITO CAPITAL', localidad = 'CARACAS' WHERE codigo = 'CAU';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('CAU', 'CAU - CAURIMARE', 'DISTRITO CAPITAL', 'CARACAS');
UPDATE oficinas SET nombre = 'CCG - CAUCAGUA', estado = 'DISTRITO CAPITAL', localidad = 'CARACAS' WHERE codigo = 'CCG';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('CCG', 'CCG - CAUCAGUA', 'DISTRITO CAPITAL', 'CARACAS');
UPDATE oficinas SET nombre = 'CCS - CARACAS', estado = 'DISTRITO CAPITAL', localidad = 'CARACAS' WHERE codigo = 'CCS';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('CCS', 'CCS - CARACAS', 'DISTRITO CAPITAL', 'CARACAS');
UPDATE oficinas SET nombre = 'CDA - CENTRO DE ATENCION', estado = 'CENTRO DE ATENCION', localidad = 'CENTRO DE ATENCION' WHERE codigo = 'CDA';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('CDA', 'CDA - CENTRO DE ATENCION', 'CENTRO DE ATENCION', 'CENTRO DE ATENCION');
UPDATE oficinas SET nombre = 'CDB - CIUDAD BOLIVAR', estado = 'BOLIVAR', localidad = 'CIUDAD BOLIVAR' WHERE codigo = 'CDB';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('CDB', 'CDB - CIUDAD BOLIVAR', 'BOLIVAR', 'CIUDAD BOLIVAR');
UPDATE oficinas SET nombre = 'CDC - CONTROL DE CAMBIOS', estado = 'CONTROL DE CAMBIOS', localidad = 'CONTROL DE CAMBIOS' WHERE codigo = 'CDC';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('CDC', 'CDC - CONTROL DE CAMBIOS', 'CONTROL DE CAMBIOS', 'CONTROL DE CAMBIOS');
UPDATE oficinas SET nombre = 'CIO - CIUDAD ORINOCO', estado = 'BOLIVAR', localidad = 'CIUDAD BOLIVAR' WHERE codigo = 'CIO';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('CIO', 'CIO - CIUDAD ORINOCO', 'BOLIVAR', 'CIUDAD BOLIVAR');
UPDATE oficinas SET nombre = 'CLA - CELINA', estado = 'ZULIA', localidad = 'PUERTOS DE ALTAGRACIA' WHERE codigo = 'CLA';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('CLA', 'CLA - CELINA', 'ZULIA', 'PUERTOS DE ALTAGRACIA');
UPDATE oficinas SET nombre = 'CLN - COLON', estado = 'TACHIRA', localidad = 'SAN JUAN DE COLON' WHERE codigo = 'CLN';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('CLN', 'CLN - COLON', 'TACHIRA', 'SAN JUAN DE COLON');
UPDATE oficinas SET nombre = 'CORP - INTERNO', estado = 'INTERNO', localidad = 'INTERNO' WHERE codigo = 'CORP';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('CORP', 'CORP - INTERNO', 'INTERNO', 'INTERNO');
UPDATE oficinas SET nombre = 'CPC - CAPACHO', estado = 'TACHIRA', localidad = 'SAN CRISTOBAL' WHERE codigo = 'CPC';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('CPC', 'CPC - CAPACHO', 'TACHIRA', 'SAN CRISTOBAL');
UPDATE oficinas SET nombre = 'CPT - CARIPITO', estado = 'MONAGAS', localidad = 'CARIPITO' WHERE codigo = 'CPT';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('CPT', 'CPT - CARIPITO', 'MONAGAS', 'CARIPITO');
UPDATE oficinas SET nombre = 'CRA - CARORA', estado = 'LARA', localidad = 'CARORA' WHERE codigo = 'CRA';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('CRA', 'CRA - CARORA', 'LARA', 'CARORA');
UPDATE oficinas SET nombre = 'CRB - LA CARABOBO', estado = 'MERIDA', localidad = 'MERIDA' WHERE codigo = 'CRB';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('CRB', 'CRB - LA CARABOBO', 'MERIDA', 'MERIDA');
UPDATE oficinas SET nombre = 'CRP - CARUPANO', estado = 'SUCRE', localidad = 'CARUPANO' WHERE codigo = 'CRP';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('CRP', 'CRP - CARUPANO', 'SUCRE', 'CARUPANO');
UPDATE oficinas SET nombre = 'CSC - CAJA SECA', estado = 'ZULIA', localidad = 'CAJA SECA' WHERE codigo = 'CSC';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('CSC', 'CSC - CAJA SECA', 'ZULIA', 'CAJA SECA');
UPDATE oficinas SET nombre = 'CTO - COLONCITO', estado = 'TACHIRA', localidad = 'COLONCITO' WHERE codigo = 'CTO';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('CTO', 'CTO - COLONCITO', 'TACHIRA', 'COLONCITO');
UPDATE oficinas SET nombre = 'CTR - CANTAURA', estado = 'ANZOATEGUI', localidad = 'ANACO' WHERE codigo = 'CTR';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('CTR', 'CTR - CANTAURA', 'ANZOATEGUI', 'ANACO');
UPDATE oficinas SET nombre = 'CUM - CUMANA', estado = 'SUCRE', localidad = 'SUCRE' WHERE codigo = 'CUM';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('CUM', 'CUM - CUMANA', 'SUCRE', 'SUCRE');
UPDATE oficinas SET nombre = 'CVE - AV ESPAÑA', estado = 'BOLIVAR', localidad = 'CIUDAD BOLIVAR' WHERE codigo = 'CVE';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('CVE', 'CVE - AV ESPAÑA', 'BOLIVAR', 'CIUDAD BOLIVAR');
UPDATE oficinas SET nombre = 'CVJ - CARVAJAL', estado = 'VALERA', localidad = 'TRUJILLO' WHERE codigo = 'CVJ';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('CVJ', 'CVJ - CARVAJAL', 'VALERA', 'TRUJILLO');
UPDATE oficinas SET nombre = 'DCC - DOS CAMINOS', estado = 'DISTRITO CAPITAL', localidad = 'CARACAS' WHERE codigo = 'DCC';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('DCC', 'DCC - DOS CAMINOS', 'DISTRITO CAPITAL', 'CARACAS');
UPDATE oficinas SET nombre = 'ECS - EL CANTON', estado = 'BARINAS', localidad = 'EL CANTON' WHERE codigo = 'ECS';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('ECS', 'ECS - EL CANTON', 'BARINAS', 'EL CANTON');
UPDATE oficinas SET nombre = 'EJI - EJIDO', estado = 'MERIDA', localidad = 'EJIDO' WHERE codigo = 'EJI';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('EJI', 'EJI - EJIDO', 'MERIDA', 'EJIDO');
UPDATE oficinas SET nombre = 'ESM - EL SOMBRERO', estado = 'GUARICO', localidad = 'EL SOMBRERO' WHERE codigo = 'ESM';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('ESM', 'ESM - EL SOMBRERO', 'GUARICO', 'EL SOMBRERO');
UPDATE oficinas SET nombre = 'GBO - EL GUAYABO', estado = 'ZULIA', localidad = 'EL GUAYABO' WHERE codigo = 'GBO';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('GBO', 'GBO - EL GUAYABO', 'ZULIA', 'EL GUAYABO');
UPDATE oficinas SET nombre = 'GYB - GUAYABONES', estado = 'MERIDA', localidad = 'EL VIGIA' WHERE codigo = 'GYB';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('GYB', 'GYB - GUAYABONES', 'MERIDA', 'EL VIGIA');
UPDATE oficinas SET nombre = 'HPT - HOYO DE LA PUERTA', estado = 'DISTRITO CAPITAL', localidad = 'CARACAS' WHERE codigo = 'HPT';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('HPT', 'HPT - HOYO DE LA PUERTA', 'DISTRITO CAPITAL', 'CARACAS');
UPDATE oficinas SET nombre = 'HUM - LA HUMBOLDT', estado = 'MERIDA', localidad = 'MERIDA' WHERE codigo = 'HUM';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('HUM', 'HUM - LA HUMBOLDT', 'MERIDA', 'MERIDA');
UPDATE oficinas SET nombre = 'JBT - JOBITOS', estado = 'ZULIA', localidad = 'PUERTOS DE ALTAGRACIA' WHERE codigo = 'JBT';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('JBT', 'JBT - JOBITOS', 'ZULIA', 'PUERTOS DE ALTAGRACIA');
UPDATE oficinas SET nombre = 'LFR - LA FRIA', estado = 'TACHIRA', localidad = 'LA FRIA' WHERE codigo = 'LFR';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('LFR', 'LFR - LA FRIA', 'TACHIRA', 'LA FRIA');
UPDATE oficinas SET nombre = 'LMG - LA MILAGROSA', estado = 'MERIDA', localidad = 'MERIDA' WHERE codigo = 'LMG';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('LMG', 'LMG - LA MILAGROSA', 'MERIDA', 'MERIDA');
UPDATE oficinas SET nombre = 'LPS - LA PEDREGOSA', estado = 'MERIDA', localidad = 'MERIDA' WHERE codigo = 'LPS';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('LPS', 'LPS - LA PEDREGOSA', 'MERIDA', 'MERIDA');
UPDATE oficinas SET nombre = 'LVR - VILLA DEL ROSARIO', estado = 'ZULIA', localidad = 'MACHIQUES' WHERE codigo = 'LVR';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('LVR', 'LVR - VILLA DEL ROSARIO', 'ZULIA', 'MACHIQUES');
UPDATE oficinas SET nombre = 'LZT - LA AZULITA', estado = 'MERIDA', localidad = 'EL VIGIA' WHERE codigo = 'LZT';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('LZT', 'LZT - LA AZULITA', 'MERIDA', 'EL VIGIA');
UPDATE oficinas SET nombre = 'MASIVO - MASIVO', estado = 'MASIVO', localidad = 'MASIVO' WHERE codigo = 'MASIVO';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('MASIVO', 'MASIVO - MASIVO', 'MASIVO', 'MASIVO');
UPDATE oficinas SET nombre = 'MAT - LA FLORESTA', estado = 'MONAGAS', localidad = 'MATURIN' WHERE codigo = 'MAT';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('MAT', 'MAT - LA FLORESTA', 'MONAGAS', 'MATURIN');
UPDATE oficinas SET nombre = 'MAZ - ZONA INDUSTRIAL', estado = 'MONAGAS', localidad = 'MATURIN' WHERE codigo = 'MAZ';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('MAZ', 'MAZ - ZONA INDUSTRIAL', 'MONAGAS', 'MATURIN');
UPDATE oficinas SET nombre = 'MBO - MARACAIBO', estado = 'ZULIA', localidad = 'MARACAIBO' WHERE codigo = 'MBO';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('MBO', 'MBO - MARACAIBO', 'ZULIA', 'MARACAIBO');
UPDATE oficinas SET nombre = 'MCC - MECOCAL', estado = 'ZULIA', localidad = 'PUERTOS DE ALTAGRACIA' WHERE codigo = 'MCC';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('MCC', 'MCC - MECOCAL', 'ZULIA', 'PUERTOS DE ALTAGRACIA');
UPDATE oficinas SET nombre = 'MCQ - MACHIQUES', estado = 'ZULIA', localidad = 'MACHIQUES' WHERE codigo = 'MCQ';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('MCQ', 'MCQ - MACHIQUES', 'ZULIA', 'MACHIQUES');
UPDATE oficinas SET nombre = 'MON - MONTALBAN', estado = 'DISTRITO CAPITAL', localidad = 'CARACAS' WHERE codigo = 'MON';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('MON', 'MON - MONTALBAN', 'DISTRITO CAPITAL', 'CARACAS');
UPDATE oficinas SET nombre = 'MRD - MERIDA', estado = 'MERIDA', localidad = 'MERIDA' WHERE codigo = 'MRD';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('MRD', 'MRD - MERIDA', 'MERIDA', 'MERIDA');
UPDATE oficinas SET nombre = 'OLV - LOS OLIVOS', estado = 'ZULIA', localidad = 'MARACAIBO' WHERE codigo = 'OLV';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('OLV', 'OLV - LOS OLIVOS', 'ZULIA', 'MARACAIBO');
UPDATE oficinas SET nombre = 'PAL - PUERTOS DE ALTAGRACIA', estado = 'ZULIA', localidad = 'PUERTOS DE ALTAGRACIA' WHERE codigo = 'PAL';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('PAL', 'PAL - PUERTOS DE ALTAGRACIA', 'ZULIA', 'PUERTOS DE ALTAGRACIA');
UPDATE oficinas SET nombre = 'PCO - CORE 8', estado = 'BOLIVAR', localidad = 'PUERTO ORDAZ' WHERE codigo = 'PCO';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('PCO', 'PCO - CORE 8', 'BOLIVAR', 'PUERTO ORDAZ');
UPDATE oficinas SET nombre = 'PDM - PUNTA DE MATA', estado = 'MONAGAS', localidad = 'MATURIN' WHERE codigo = 'PDM';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('PDM', 'PDM - PUNTA DE MATA', 'MONAGAS', 'MATURIN');
UPDATE oficinas SET nombre = 'PGD - PALO GORDO', estado = 'TACHIRA', localidad = 'SAN CRISTOBAL' WHERE codigo = 'PGD';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('PGD', 'PGD - PALO GORDO', 'TACHIRA', 'SAN CRISTOBAL');
UPDATE oficinas SET nombre = 'PTO - PUERTO ORDAZ', estado = 'BOLIVAR', localidad = 'PUERTO ORDAZ' WHERE codigo = 'PTO';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('PTO', 'PTO - PUERTO ORDAZ', 'BOLIVAR', 'PUERTO ORDAZ');
UPDATE oficinas SET nombre = 'RBO - RUBIO', estado = 'TACHIRA', localidad = 'SAN CRISTOBAL' WHERE codigo = 'RBO';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('RBO', 'RBO - RUBIO', 'TACHIRA', 'SAN CRISTOBAL');
UPDATE oficinas SET nombre = 'SAT - SAN ANTONIO DEL TACHIRA', estado = 'TACHIRA', localidad = 'SAN ANTONIO DEL TACHIRA' WHERE codigo = 'SAT';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('SAT', 'SAT - SAN ANTONIO DEL TACHIRA', 'TACHIRA', 'SAN ANTONIO DEL TACHIRA');
UPDATE oficinas SET nombre = 'SBE - SAN BERNARDINO', estado = 'DISTRITO CAPITAL', localidad = 'CARACAS' WHERE codigo = 'SBE';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('SBE', 'SBE - SAN BERNARDINO', 'DISTRITO CAPITAL', 'CARACAS');
UPDATE oficinas SET nombre = 'SCP - SOCOPO', estado = 'BARINAS', localidad = 'SOCOPO' WHERE codigo = 'SCP';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('SCP', 'SCP - SOCOPO', 'BARINAS', 'SOCOPO');
UPDATE oficinas SET nombre = 'SCR - SAN CRISTOBAL', estado = 'TACHIRA', localidad = 'SAN CRISTOBAL' WHERE codigo = 'SCR';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('SCR', 'SCR - SAN CRISTOBAL', 'TACHIRA', 'SAN CRISTOBAL');
UPDATE oficinas SET nombre = 'SCZ - SAN CARLOS', estado = 'ZULIA', localidad = 'SANTA BARBARA' WHERE codigo = 'SCZ';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('SCZ', 'SCZ - SAN CARLOS', 'ZULIA', 'SANTA BARBARA');
UPDATE oficinas SET nombre = 'SEA - SANTA ELENA DE ARENALES', estado = 'MERIDA', localidad = 'EL VIGIA' WHERE codigo = 'SEA';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('SEA', 'SEA - SANTA ELENA DE ARENALES', 'MERIDA', 'EL VIGIA');
UPDATE oficinas SET nombre = 'SFX - SAN FELIX', estado = 'BOLIVAR', localidad = 'PUERTO ORDAZ' WHERE codigo = 'SFX';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('SFX', 'SFX - SAN FELIX', 'BOLIVAR', 'PUERTO ORDAZ');
UPDATE oficinas SET nombre = 'SJM - SAN JUAN DE LOS MORROS', estado = 'GUARICO', localidad = 'SAN JUAN DE LOS MORROS' WHERE codigo = 'SJM';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('SJM', 'SJM - SAN JUAN DE LOS MORROS', 'GUARICO', 'SAN JUAN DE LOS MORROS');
UPDATE oficinas SET nombre = 'SJP - SAN JOSE DE PERIJA', estado = 'ZULIA', localidad = 'MACHIQUES' WHERE codigo = 'SJP';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('SJP', 'SJP - SAN JOSE DE PERIJA', 'ZULIA', 'MACHIQUES');
UPDATE oficinas SET nombre = 'SMI - SANTA MARIA DE IPIRE', estado = 'GUARICO', localidad = 'SANTA MARIA DE IPIRE' WHERE codigo = 'SMI';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('SMI', 'SMI - SANTA MARIA DE IPIRE', 'GUARICO', 'SANTA MARIA DE IPIRE');
UPDATE oficinas SET nombre = 'STB - SANTA BARBARA DE BARINAS', estado = 'BARINAS', localidad = 'BARINAS' WHERE codigo = 'STB';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('STB', 'STB - SANTA BARBARA DE BARINAS', 'BARINAS', 'BARINAS');
UPDATE oficinas SET nombre = 'STF - SANTA FE', estado = 'DISTRITO CAPITAL', localidad = 'CARACAS' WHERE codigo = 'STF';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('STF', 'STF - SANTA FE', 'DISTRITO CAPITAL', 'CARACAS');
UPDATE oficinas SET nombre = 'SVZ - SANTA BARBARA DEL ZULIA', estado = 'ZULIA', localidad = 'SANTA BARBARA DEL ZULIA' WHERE codigo = 'SVZ';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('SVZ', 'SVZ - SANTA BARBARA DEL ZULIA', 'ZULIA', 'SANTA BARBARA DEL ZULIA');
UPDATE oficinas SET nombre = 'TBY - TABAY', estado = 'MERIDA', localidad = 'MERIDA' WHERE codigo = 'TBY';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('TBY', 'TBY - TABAY', 'MERIDA', 'MERIDA');
UPDATE oficinas SET nombre = 'TGO - EL TIGRITO', estado = 'ANZOATEGUI', localidad = 'EL TIGRE' WHERE codigo = 'TGO';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('TGO', 'TGO - EL TIGRITO', 'ANZOATEGUI', 'EL TIGRE');
UPDATE oficinas SET nombre = 'TGR - EL TIGRE', estado = 'ANZOATEGUI', localidad = 'EL TIGRE' WHERE codigo = 'TGR';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('TGR', 'TGR - EL TIGRE', 'ANZOATEGUI', 'EL TIGRE');
UPDATE oficinas SET nombre = 'TMB - TEMBLADOR', estado = 'MONAGAS', localidad = 'TEMBLADOR' WHERE codigo = 'TMB';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('TMB', 'TMB - TEMBLADOR', 'MONAGAS', 'TEMBLADOR');
UPDATE oficinas SET nombre = 'TPR - TIPURO', estado = 'MONAGAS', localidad = 'MATURIN' WHERE codigo = 'TPR';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('TPR', 'TPR - TIPURO', 'MONAGAS', 'MATURIN');
UPDATE oficinas SET nombre = 'TRB - TARIBA', estado = 'TACHIRA', localidad = 'SAN CRISTOBAL' WHERE codigo = 'TRB';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('TRB', 'TRB - TARIBA', 'TACHIRA', 'SAN CRISTOBAL');
UPDATE oficinas SET nombre = 'UNA - UREÑA', estado = 'TACHIRA', localidad = 'UREÑA' WHERE codigo = 'UNA';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('UNA', 'UNA - UREÑA', 'TACHIRA', 'UREÑA');
UPDATE oficinas SET nombre = 'VAL - PASEO LAS INDUSTRIAS', estado = 'CARABOBO', localidad = 'VALENCIA' WHERE codigo = 'VAL';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('VAL', 'VAL - PASEO LAS INDUSTRIAS', 'CARABOBO', 'VALENCIA');
UPDATE oficinas SET nombre = 'VBF - BELLA FLORIDA', estado = 'CARABOBO', localidad = 'VALENCIA' WHERE codigo = 'VBF';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('VBF', 'VBF - BELLA FLORIDA', 'CARABOBO', 'VALENCIA');
UPDATE oficinas SET nombre = 'VBN - BOLIVAR NORTE', estado = 'CARABOBO', localidad = 'VALENCIA' WHERE codigo = 'VBN';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('VBN', 'VBN - BOLIVAR NORTE', 'CARABOBO', 'VALENCIA');
UPDATE oficinas SET nombre = 'VDP - VALLE DE LA PASCUA', estado = 'GUARICO', localidad = 'VALLE DE LA PASCUA' WHERE codigo = 'VDP';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('VDP', 'VDP - VALLE DE LA PASCUA', 'GUARICO', 'VALLE DE LA PASCUA');
UPDATE oficinas SET nombre = 'VIC - AV VICTORIA', estado = 'DISTRITO CAPITAL', localidad = 'CARACAS' WHERE codigo = 'VIC';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('VIC', 'VIC - AV VICTORIA', 'DISTRITO CAPITAL', 'CARACAS');
UPDATE oficinas SET nombre = 'VIG - EL VIGIA', estado = 'MERIDA', localidad = 'EL VIGIA' WHERE codigo = 'VIG';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('VIG', 'VIG - EL VIGIA', 'MERIDA', 'EL VIGIA');
UPDATE oficinas SET nombre = 'VLR - VALERA', estado = 'TRUJILLO', localidad = 'VALERA' WHERE codigo = 'VLR';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('VLR', 'VLR - VALERA', 'TRUJILLO', 'VALERA');
UPDATE oficinas SET nombre = 'SGU - SAN AGUSTIN', estado = 'DISTRITO CAPITAL', localidad = 'CARACAS' WHERE codigo = 'SGU';
INSERT OR IGNORE INTO oficinas (codigo, nombre, estado, localidad) VALUES ('SGU', 'SGU - SAN AGUSTIN', 'DISTRITO CAPITAL', 'CARACAS');
