name = "vnet-fallas-masivas"
compatibility_date = "2024-09-01"
pages_build_output_dir = "public"

# Este binding conecta las funciones en /functions con la base de datos D1.
# El database_id se obtiene al crear la base con: wrangler d1 create vnet_fallas_masivas
[[d1_databases]]
binding = "DB"
database_name = "vnet_fallas_masivas"
database_id = "49d7c81a-56d7-4cfb-b0f4-6f85166013f7"
